# Generated by Django 5.2.4 on 2025-08-24 08:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit_loss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitlossrecord',
            name='gross_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross profit (income - cost of goods sold)', max_digits=15),
        ),
        migrations.AddField(
            model_name='profitlossrecord',
            name='gross_profit_margin_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross profit margin as percentage of sales', max_digits=5),
        ),
        migrations.AddField(
            model_name='profitlossrecord',
            name='total_cost_of_goods_sold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cost of goods sold in this period', max_digits=15),
        ),
        migrations.AlterField(
            model_name='profitlossrecord',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net profit (gross profit - total expenses)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='profitlossrecord',
            name='profit_margin_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net profit margin as percentage of sales', max_digits=5),
        ),
    ]
