name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1
assets:
  - assets/fonts/Jameel Noori Nastaleeq Regular.ttf
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  provider:

  # Desktop Window Management
  bitsdojo_window:
  desktop_multi_window:

  # Responsive Design
  sizer:

  # Additional Premium Features
  google_fonts:
  flutter_svg:
  animations:
  flutter_animate:
  file_picker:
  path:
  path_provider:
  syncfusion_flutter_datepicker:
  dio:
  shared_preferences:
  json_annotation:
  intl:
  # Export functionality
  pdf: ^3.10.7
  excel: ^2.1.0
  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix:
  flutter_lints: ^5.0.0
  json_serializable:
  build_runner:

flutter:
  generate: true
  uses-material-design: true

