# Generated by Django 5.2.4 on 2025-08-13 14:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(help_text='Cached customer name at time of order', max_length=200)),
                ('customer_phone', models.CharField(help_text='Cached customer phone at time of order', max_length=20)),
                ('customer_email', models.EmailField(blank=True, help_text='Cached customer email at time of order', max_length=254)),
                ('advance_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid in advance', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total order amount (calculated from order items)', max_digits=15)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Remaining amount to be paid', max_digits=15)),
                ('is_fully_paid', models.BooleanField(default=False, help_text='Whether the order is fully paid')),
                ('date_ordered', models.DateField(default=django.utils.timezone.now, help_text='Date when order was placed')),
                ('expected_delivery_date', models.DateField(blank=True, help_text='Expected delivery date', null=True)),
                ('description', models.TextField(blank=True, help_text='Order description and notes')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('IN_PRODUCTION', 'In Production'), ('READY', 'Ready for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current order status', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer who placed the order', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'order',
                'ordering': ['-date_ordered', '-created_at'],
                'indexes': [models.Index(fields=['customer'], name='order_custome_7c3d15_idx'), models.Index(fields=['status'], name='order_status_35c31c_idx'), models.Index(fields=['date_ordered'], name='order_date_or_488026_idx'), models.Index(fields=['expected_delivery_date'], name='order_expecte_008f15_idx'), models.Index(fields=['is_active'], name='order_is_acti_427ef6_idx'), models.Index(fields=['created_at'], name='order_created_6dbd10_idx'), models.Index(fields=['is_fully_paid'], name='order_is_full_38f960_idx')],
            },
        ),
    ]
