# Generated by Django 5.2.4 on 2025-08-16 11:42

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='conversion_date',
            field=models.DateTimeField(blank=True, help_text='Date when order was first converted to sale', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='conversion_status',
            field=models.CharField(choices=[('NOT_CONVERTED', 'Not Converted'), ('PARTIALLY_CONVERTED', 'Partially Converted'), ('FULLY_CONVERTED', 'Fully Converted')], default='NOT_CONVERTED', help_text='Status of order conversion to sales', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='converted_sales_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount converted to sales', max_digits=15),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['conversion_status'], name='order_convers_bc19fd_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['conversion_date'], name='order_convers_149d51_idx'),
        ),
    ]
