# Generated by Django 6.0.2 on 2026-04-09 10:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        ('products', '0005_alter_product_pieces'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(help_text='Cached customer name', max_length=200)),
                ('customer_phone', models.CharField(help_text='Cached customer phone', max_length=20)),
                ('customer_email', models.EmailField(blank=True, help_text='Cached customer email', max_length=254)),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total before discount and tax', max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount applied', max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax applied', max_digits=15)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final quotation amount', max_digits=15)),
                ('date_issued', models.DateField(default=django.utils.timezone.now, help_text='Date when quotation was created')),
                ('expiry_date', models.DateField(help_text='When this quotation expires')),
                ('description', models.TextField(blank=True, help_text='General notes')),
                ('terms_conditions', models.TextField(blank=True, help_text='Terms and conditions')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', help_text='Current status', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversion_status', models.CharField(choices=[('NOT_CONVERTED', 'Not Converted'), ('CONVERTED_TO_SALE', 'Converted to Sale'), ('CONVERTED_TO_ORDER', 'Converted to Order')], default='NOT_CONVERTED', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer requesting the quotation', on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotations',
                'db_table': 'quotation',
                'ordering': ['-date_issued', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_items', to='products.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotation')),
            ],
            options={
                'verbose_name': 'Quotation Item',
                'verbose_name_plural': 'Quotation Items',
                'db_table': 'quotation_item',
                'ordering': ['created_at'],
            },
        ),
    ]
