# Generated by Django 6.0.2 on 2026-04-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='quotation_number',
            field=models.CharField(blank=True, help_text='Custom quotation number', max_length=100, null=True),
        ),
    ]
