# Generated by Django 5.2.4 on 2025-08-28 15:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_cost_price_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_stock_level',
            field=models.PositiveIntegerField(default=100, help_text='Maximum stock level to maintain'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Minimum stock level before low stock warning'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_available',
            field=models.PositiveIntegerField(default=0, help_text='Available quantity excluding reserved stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_reserved',
            field=models.PositiveIntegerField(default=0, help_text='Quantity currently reserved for pending sales'),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_point',
            field=models.PositiveIntegerField(default=10, help_text='Stock level at which to reorder'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StockChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_quantity', models.PositiveIntegerField(help_text='Quantity before change')),
                ('new_quantity', models.PositiveIntegerField(help_text='Quantity after change')),
                ('change_type', models.CharField(choices=[('SALE_CONFIRMATION', 'Sale Confirmation'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment'), ('RESTOCK', 'Restock'), ('RETURN', 'Return'), ('DAMAGE', 'Damage'), ('BULK_UPDATE', 'Bulk Update'), ('SYSTEM_CORRECTION', 'System Correction')], help_text='Type of stock change', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for the stock change')),
                ('reference_id', models.CharField(blank=True, help_text='Reference ID (sale, order, etc.)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_changes', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_changes', to='products.product')),
            ],
            options={
                'verbose_name': 'Stock Change Log',
                'verbose_name_plural': 'Stock Change Logs',
                'db_table': 'stock_change_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='stock_chang_product_df5cd4_idx'), models.Index(fields=['change_type', 'created_at'], name='stock_chang_change__02c709_idx'), models.Index(fields=['changed_by', 'created_at'], name='stock_chang_changed_d52462_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_id', models.CharField(help_text='ID of the sale this reservation is for', max_length=100)),
                ('quantity_reserved', models.PositiveIntegerField(help_text='Quantity reserved for this sale')),
                ('reserved_until', models.DateTimeField(help_text='When this reservation expires')),
                ('is_confirmed', models.BooleanField(default=False, help_text='Whether this reservation has been confirmed')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When this reservation was confirmed', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this reservation is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='products.product')),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Reservation',
                'verbose_name_plural': 'Stock Reservations',
                'db_table': 'stock_reservation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'is_active'], name='stock_reser_product_09ee21_idx'), models.Index(fields=['sale_id', 'is_active'], name='stock_reser_sale_id_fbc2a9_idx'), models.Index(fields=['reserved_until'], name='stock_reser_reserve_28f01f_idx'), models.Index(fields=['is_confirmed'], name='stock_reser_is_conf_14f8cb_idx')],
            },
        ),
    ]
