# Generated by Django 6.0.2 on 2026-03-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_barcode_product_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_stock_level',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Maximum stock level to maintain', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock_threshold',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Minimum stock level before low stock warning', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Available quantity in stock', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_available',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Available quantity excluding reserved stock', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_reserved',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity currently reserved for pending sales', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_point',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Stock level at which to reorder', max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockchangelog',
            name='new_quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity after change', max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockchangelog',
            name='old_quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity before change', max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='quantity_reserved',
            field=models.DecimalField(decimal_places=2, help_text='Quantity reserved for this sale', max_digits=12),
        ),
    ]
