# Generated by Django 6.0.2 on 2026-04-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_max_stock_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fabric',
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(default='', help_text='Material type', max_length=100),
            preserve_default=False,
        ),
    ]
