# Generated by Django 6.0.2 on 2026-04-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_fabric_product_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pieces',
            field=models.JSONField(blank=True, default=list, help_text="Array of product pieces (e.g., ['Handle', 'Tap', 'Valve'])"),
        ),
    ]
