# Generated by Django 6.0.2 on 2026-05-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principalaccount',
            name='handled_by',
            field=models.CharField(blank=True, choices=[('MetaBrass Admin', 'MetaBrass Admin')], help_text='Person who handled this transaction', max_length=100, null=True),
        ),
    ]
