# Generated by Django 5.2.4 on 2025-08-13 12:18

import advance_payments.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('labor_name', models.CharField(help_text='Cached labor name at time of payment', max_length=200)),
                ('labor_phone', models.CharField(help_text='Cached labor phone at time of payment', max_length=20)),
                ('labor_role', models.CharField(help_text='Cached labor designation/role at time of payment', max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Advance amount given to labor', max_digits=10, validators=[advance_payments.models.validate_advance_amount])),
                ('description', models.TextField(blank=True, help_text='Purpose or description of the advance payment')),
                ('date', models.DateField(help_text='Date when advance payment was made', validators=[advance_payments.models.validate_payment_date])),
                ('time', models.TimeField(default=django.utils.timezone.now, help_text='Time when advance payment was made')),
                ('receipt_image_path', models.ImageField(blank=True, help_text='Receipt image for the advance payment', null=True, upload_to=advance_payments.models.advance_payment_upload_path)),
                ('remaining_salary', models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining salary after this advance', max_digits=10)),
                ('total_salary', models.DecimalField(decimal_places=2, help_text="Labor's total monthly salary at time of payment", max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_advance_payments', to=settings.AUTH_USER_MODEL)),
                ('labor', models.ForeignKey(help_text='Labor receiving the advance payment', on_delete=django.db.models.deletion.PROTECT, related_name='advance_payments', to='labors.labor')),
            ],
            options={
                'verbose_name': 'Advance Payment',
                'verbose_name_plural': 'Advance Payments',
                'db_table': 'advance_payment',
                'ordering': ['-date', '-time', '-created_at'],
                'indexes': [models.Index(fields=['labor'], name='advance_pay_labor_i_cd89f6_idx'), models.Index(fields=['labor_name'], name='advance_pay_labor_n_4763c8_idx'), models.Index(fields=['labor_phone'], name='advance_pay_labor_p_0cef49_idx'), models.Index(fields=['labor_role'], name='advance_pay_labor_r_dca472_idx'), models.Index(fields=['date'], name='advance_pay_date_98db74_idx'), models.Index(fields=['amount'], name='advance_pay_amount_832771_idx'), models.Index(fields=['is_active'], name='advance_pay_is_acti_0c1d77_idx'), models.Index(fields=['created_at'], name='advance_pay_created_d61ef7_idx'), models.Index(fields=['-date', '-time'], name='advance_pay_date_8b9beb_idx')],
            },
        ),
    ]
