# Generated by Django 5.2.4 on 2025-08-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance_payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepayment',
            name='time',
            field=models.TimeField(help_text='Time when advance payment was made'),
        ),
    ]
