# Generated by Django 5.2.4 on 2025-08-14 08:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creditor_name', models.CharField(help_text='Name of creditor/lender', max_length=200)),
                ('creditor_phone', models.CharField(blank=True, help_text='Creditor contact number', max_length=20)),
                ('creditor_email', models.EmailField(blank=True, help_text='Optional creditor email', max_length=254)),
                ('amount_borrowed', models.DecimalField(decimal_places=2, help_text='Original borrowed amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid so far', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reason_or_item', models.TextField(help_text='Description of what was borrowed for')),
                ('date_borrowed', models.DateField(help_text='When the amount was borrowed')),
                ('expected_repayment_date', models.DateField(help_text='When repayment is due')),
                ('balance_remaining', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated remaining balance', max_digits=12)),
                ('is_fully_paid', models.BooleanField(default=False, help_text='Auto-calculated payment status')),
                ('payment_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated percentage paid', max_digits=5)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('PARTIALLY_PAID', 'Partially Paid'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes and payment history')),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payables', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, help_text='Link to vendor if creditor is a registered vendor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payables', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Payable',
                'verbose_name_plural': 'Payables',
                'db_table': 'payable',
                'ordering': ['-created_at', '-expected_repayment_date'],
            },
        ),
        migrations.CreateModel(
            name='PayablePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, help_text='Payment notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payables.payable')),
            ],
            options={
                'verbose_name': 'Payable Payment',
                'verbose_name_plural': 'Payable Payments',
                'db_table': 'payable_payment',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['creditor_name'], name='payable_credito_d97fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['status'], name='payable_status_cd1b61_idx'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['priority'], name='payable_priorit_9f5723_idx'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['is_fully_paid'], name='payable_is_full_26a6c3_idx'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['expected_repayment_date'], name='payable_expecte_6966d8_idx'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['date_borrowed'], name='payable_date_bo_cea8f5_idx'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['is_active'], name='payable_is_acti_1948ad_idx'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['created_at'], name='payable_created_9e902e_idx'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['vendor'], name='payable_vendor__19838d_idx'),
        ),
        migrations.AddIndex(
            model_name='payablepayment',
            index=models.Index(fields=['payable'], name='payable_pay_payable_a853a3_idx'),
        ),
        migrations.AddIndex(
            model_name='payablepayment',
            index=models.Index(fields=['payment_date'], name='payable_pay_payment_bbf3db_idx'),
        ),
        migrations.AddIndex(
            model_name='payablepayment',
            index=models.Index(fields=['created_at'], name='payable_pay_created_912a93_idx'),
        ),
    ]
