# Generated by Django 5.2.4 on 2025-08-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payable',
            name='creditor_email',
            field=models.EmailField(blank=True, help_text='Optional creditor email', max_length=254, null=True),
        ),
    ]
