# Generated by Django 5.2.4 on 2025-08-06 07:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Customer full name', max_length=200)),
                ('phone', models.CharField(help_text='Customer phone number (any format)', max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Customer email address', max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('address', models.TextField(blank=True, help_text='Customer address')),
                ('city', models.CharField(blank=True, help_text='Customer city/location', max_length=100)),
                ('country', models.CharField(default='Pakistan', help_text='Customer country', max_length=100)),
                ('customer_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('BUSINESS', 'Business')], default='INDIVIDUAL', help_text='Type of customer', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New Customer'), ('REGULAR', 'Regular Customer'), ('VIP', 'VIP Customer'), ('INACTIVE', 'Inactive Customer')], default='NEW', help_text='Customer status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the customer')),
                ('phone_verified', models.BooleanField(default=False, help_text='Whether phone number is verified')),
                ('email_verified', models.BooleanField(default=False, help_text='Whether email is verified')),
                ('business_name', models.CharField(blank=True, help_text='Business name (for business customers)', max_length=200)),
                ('tax_number', models.CharField(blank=True, help_text='Tax/NTN number (for business customers)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_order_date', models.DateTimeField(blank=True, help_text='Date of last order', null=True)),
                ('last_contact_date', models.DateTimeField(blank=True, help_text='Date of last contact', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customer',
                'ordering': ['-created_at', 'name'],
                'indexes': [models.Index(fields=['name'], name='customer_name_364ac9_idx'), models.Index(fields=['phone'], name='customer_phone_ea919e_idx'), models.Index(fields=['email'], name='customer_email_c21aac_idx'), models.Index(fields=['status'], name='customer_status_7c387b_idx'), models.Index(fields=['customer_type'], name='customer_custome_7671c8_idx'), models.Index(fields=['is_active'], name='customer_is_acti_13da22_idx'), models.Index(fields=['country'], name='customer_country_0c81b5_idx'), models.Index(fields=['created_at'], name='customer_created_f84797_idx')],
            },
        ),
    ]
