# Generated by Django 5.2.4 on 2025-08-12 07:18

import django.core.validators
import django.db.models.deletion
import labors.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name of the labor', max_length=200)),
                ('cnic', models.CharField(help_text='Pakistani CNIC in format: 12345-1234567-1', max_length=15, unique=True, validators=[labors.models.validate_pakistani_cnic])),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in valid format', regex='^[\\+]?[0-9\\-\\s]{10,20}$')])),
                ('caste', models.CharField(help_text='Caste/community of the labor', max_length=100)),
                ('designation', models.CharField(help_text='Job designation/position', max_length=150)),
                ('joining_date', models.DateField(help_text='Date when labor joined', validators=[labors.models.validate_joining_date])),
                ('salary', models.DecimalField(decimal_places=2, help_text='Monthly salary amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('area', models.CharField(help_text='Area/locality within the city', max_length=100)),
                ('city', models.CharField(help_text='City where labor is located', max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Gender of the labor', max_length=1)),
                ('age', models.PositiveIntegerField(help_text='Age of the labor', validators=[django.core.validators.MinValueValidator(16, 'Minimum age must be 16 years'), django.core.validators.MaxValueValidator(70, 'Maximum age must be 70 years')])),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_labors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Labor',
                'verbose_name_plural': 'Labors',
                'db_table': 'labor',
                'ordering': ['-created_at', 'name'],
                'indexes': [models.Index(fields=['name'], name='labor_name_1e3af0_idx'), models.Index(fields=['cnic'], name='labor_cnic_176622_idx'), models.Index(fields=['phone_number'], name='labor_phone_n_e96671_idx'), models.Index(fields=['designation'], name='labor_designa_91103f_idx'), models.Index(fields=['caste'], name='labor_caste_bec34e_idx'), models.Index(fields=['city'], name='labor_city_db5ec1_idx'), models.Index(fields=['area'], name='labor_area_f7c086_idx'), models.Index(fields=['gender'], name='labor_gender_8a0722_idx'), models.Index(fields=['joining_date'], name='labor_joining_8c3df9_idx'), models.Index(fields=['salary'], name='labor_salary_a16daf_idx'), models.Index(fields=['is_active'], name='labor_is_acti_3fd9fa_idx'), models.Index(fields=['created_at'], name='labor_created_6295e2_idx')],
            },
        ),
    ]
