# Generated by Django 4.2.7 on 2025-01-27 12:00:00

from django.db import migrations, models
import decimal


class Migration(migrations.Migration):

    dependencies = [
        ('labors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labor',
            name='remaining_monthly_salary',
            field=models.DecimalField(
                decimal_places=2,
                default=decimal.Decimal('0.00'),
                help_text='Remaining salary balance for current month (resets monthly)',
                max_digits=10
            ),
        ),
        migrations.AddField(
            model_name='labor',
            name='current_month',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Current month number (1-12) for tracking monthly resets'
            ),
        ),
        migrations.AddField(
            model_name='labor',
            name='current_year',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Current year for tracking monthly resets'
            ),
        ),
    ]


