# Generated by Django 6.0.2 on 2026-03-28 08:04

import labors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labors', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labor',
            name='cnic',
            field=models.CharField(blank=True, help_text='Pakistani CNIC in format: 12345-1234567-1', max_length=15, null=True, unique=True, validators=[labors.models.validate_pakistani_cnic]),
        ),
    ]
