# Generated by Django 4.2.7 on 2025-01-27 12:00:00

from django.db import migrations
from datetime import date


def initialize_monthly_salary(apps, schema_editor):
    """Initialize existing labors with their full salary as remaining monthly salary"""
    Labor = apps.get_model('labors', 'Labor')
    today = date.today()
    
    for labor in Labor.objects.all():
        labor.remaining_monthly_salary = labor.salary
        labor.current_month = today.month
        labor.current_year = today.year
        labor.save()


def reverse_initialize_monthly_salary(apps, schema_editor):
    """Reverse the initialization (set to 0)"""
    Labor = apps.get_model('labors', 'Labor')
    
    for labor in Labor.objects.all():
        labor.remaining_monthly_salary = 0
        labor.current_month = 0
        labor.current_year = 0
        labor.save()


class Migration(migrations.Migration):

    dependencies = [
        ('labors', '0002_add_monthly_salary_tracking'),
    ]

    operations = [
        migrations.RunPython(
            initialize_monthly_salary,
            reverse_initialize_monthly_salary
        ),
    ]


