# Generated by Django 6.0.2 on 2026-03-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labors', '0003_alter_labor_cnic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labor',
            name='caste',
            field=models.CharField(blank=True, help_text='Caste/community of the labor', max_length=100, null=True),
        ),
    ]
