# Generated by Django 5.2.4 on 2025-01-16 12:00:00

import django.db.models.deletion
import django.utils.timezone
import sales.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        # Create TaxRate model
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tax rate name (e.g., Standard GST, Reduced GST, FED on Textiles)', max_length=100)),
                ('tax_type', models.CharField(choices=[('GST', 'General Sales Tax'), ('FED', 'Federal Excise Duty'), ('WHT', 'Withholding Tax'), ('ADDITIONAL', 'Additional Tax'), ('CUSTOM', 'Custom Tax Rate')], default='GST', help_text='Type of tax', max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Tax rate percentage (e.g., 17.00 for 17%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tax rate is currently active')),
                ('description', models.TextField(blank=True, help_text='Description of when this tax rate applies')),
                ('effective_from', models.DateField(default=django.utils.timezone.now, help_text='Date from which this tax rate is effective')),
                ('effective_to', models.DateField(blank=True, help_text='Date until which this tax rate is effective (null for indefinite)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax Rate',
                'verbose_name_plural': 'Tax Rates',
                'db_table': 'tax_rates',
                'ordering': ['tax_type', 'effective_from'],
            },
        ),
        
        # Add tax_configuration field to Sales model
        migrations.AddField(
            model_name='sales',
            name='tax_configuration',
            field=models.JSONField(default=dict, help_text='JSON configuration for multiple tax types and rates'),
        ),
        
        # Update SaleItem order_item field to be a proper ForeignKey
        migrations.AlterField(
            model_name='saleitem',
            name='order_item',
            field=models.ForeignKey(blank=True, help_text='Optional: Order item this sale item was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='order_items.orderitem'),
        ),
        
        # Add indexes for TaxRate
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['tax_type', 'is_active'], name='tax_rates_tax_type_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['effective_from', 'effective_to'], name='tax_rates_effective_dates_idx'),
        ),
    ]
