# Generated by Django 5.2.4 on 2025-01-16 12:00:00

from django.db import migrations
from decimal import Decimal
from datetime import date


def populate_default_tax_rates(apps, schema_editor):
    """Populate default tax rates for Pakistan's tax system"""
    TaxRate = apps.get_model('sales', 'TaxRate')
    
    # Default GST rates
    TaxRate.objects.create(
        name='Standard GST',
        tax_type='GST',
        percentage=Decimal('17.00'),
        description='Standard General Sales Tax rate for most goods and services in Pakistan',
        effective_from=date(2024, 1, 1),
        is_active=True
    )
    
    TaxRate.objects.create(
        name='Reduced GST (Textiles)',
        tax_type='GST',
        percentage=Decimal('12.00'),
        description='Reduced GST rate for textile and clothing items',
        effective_from=date(2024, 1, 1),
        is_active=True
    )
    
    TaxRate.objects.create(
        name='Zero GST (Essential Items)',
        tax_type='GST',
        percentage=Decimal('0.00'),
        description='Zero GST rate for essential food items and medicines',
        effective_from=date(2024, 1, 1),
        is_active=True
    )
    
    # Federal Excise Duty rates
    TaxRate.objects.create(
        name='FED on Luxury Items',
        tax_type='FED',
        percentage=Decimal('5.00'),
        description='Federal Excise Duty on luxury and non-essential items',
        effective_from=date(2024, 1, 1),
        is_active=True
    )
    
    TaxRate.objects.create(
        name='FED on Tobacco',
        tax_type='FED',
        percentage=Decimal('15.00'),
        description='Federal Excise Duty on tobacco products',
        effective_from=date(2024, 1, 1),
        is_active=True
    )
    
    # Withholding Tax rates
    TaxRate.objects.create(
        name='WHT on Services',
        tax_type='WHT',
        percentage=Decimal('3.00'),
        description='Withholding Tax on services provided',
        effective_from=date(2024, 1, 1),
        is_active=True
    )
    
    TaxRate.objects.create(
        name='WHT on Goods',
        tax_type='WHT',
        percentage=Decimal('2.00'),
        description='Withholding Tax on goods supplied',
        effective_from=date(2024, 1, 1),
        is_active=True
    )
    
    # Additional taxes
    TaxRate.objects.create(
        name='Additional Tax (Luxury)',
        tax_type='ADDITIONAL',
        percentage=Decimal('3.00'),
        description='Additional tax on luxury items and high-value transactions',
        effective_from=date(2024, 1, 1),
        is_active=True
    )
    
    TaxRate.objects.create(
        name='Custom Tax Rate',
        tax_type='CUSTOM',
        percentage=Decimal('0.00'),
        description='Custom tax rate for special circumstances (to be configured per sale)',
        effective_from=date(2024, 1, 1),
        is_active=True
    )


def reverse_populate_default_tax_rates(apps, schema_editor):
    """Reverse the population of default tax rates"""
    TaxRate = apps.get_model('sales', 'TaxRate')
    TaxRate.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_tax_system_upgrade'),
    ]

    operations = [
        migrations.RunPython(
            populate_default_tax_rates,
            reverse_populate_default_tax_rates
        ),
    ]
