# Generated by Django 5.2.4 on 2025-08-28 12:56

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('payments', '0002_alter_payment_receipt_image_path'),
        ('sales', '0003_populate_default_tax_rates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(help_text='Unique invoice number', max_length=20, unique=True)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time invoice was issued')),
                ('due_date', models.DateTimeField(blank=True, help_text='Payment due date (optional)', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('SENT', 'Sent to Customer'), ('VIEWED', 'Viewed by Customer'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Current invoice status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional invoice notes')),
                ('terms_conditions', models.TextField(blank=True, help_text='Terms and conditions for this invoice')),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF invoice file', null=True, upload_to='invoices/')),
                ('email_sent', models.BooleanField(default=False, help_text='Whether invoice was emailed to customer')),
                ('email_sent_at', models.DateTimeField(blank=True, help_text='When invoice was last emailed', null=True)),
                ('viewed_at', models.DateTimeField(blank=True, help_text='When customer last viewed the invoice', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'sales_invoice',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(help_text='Unique receipt number', max_length=20, unique=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When receipt was generated')),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('SENT', 'Sent to Customer'), ('VIEWED', 'Viewed by Customer'), ('ARCHIVED', 'Archived')], default='GENERATED', help_text='Current receipt status', max_length=20)),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF receipt file', null=True, upload_to='receipts/')),
                ('email_sent', models.BooleanField(default=False, help_text='Whether receipt was emailed to customer')),
                ('email_sent_at', models.DateTimeField(blank=True, help_text='When receipt was last emailed', null=True)),
                ('viewed_at', models.DateTimeField(blank=True, help_text='When customer last viewed the receipt', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional receipt notes')),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'db_table': 'sales_receipt',
                'ordering': ['-generated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_number', models.CharField(help_text='Unique refund number', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to be refunded', max_digits=10)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHECK', 'Check'), ('CREDIT_NOTE', 'Credit Note'), ('OTHER', 'Other')], help_text='Refund method', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of refund', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='External reference number (check number, transfer ID, etc.)', max_length=100)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When refund was processed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the refund')),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'db_table': 'sales_refund',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(help_text='Unique return number', max_length=50, unique=True)),
                ('reason', models.CharField(choices=[('DEFECTIVE', 'Defective Product'), ('WRONG_ITEM', 'Wrong Item Received'), ('DAMAGED', 'Damaged in Transit'), ('SIZE_ISSUE', 'Size/Fit Issue'), ('QUALITY_ISSUE', 'Quality Issue'), ('CUSTOMER_REQUEST', 'Customer Request'), ('OTHER', 'Other')], help_text='Primary reason for return', max_length=20)),
                ('reason_details', models.TextField(blank=True, help_text='Detailed explanation of return reason')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROCESSED', 'Processed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of return request', max_length=20)),
                ('return_date', models.DateTimeField(auto_now_add=True, help_text='When return was requested')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When return was approved', null=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When return was processed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the return')),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Return',
                'verbose_name_plural': 'Returns',
                'db_table': 'sales_return',
                'ordering': ['-return_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.PositiveIntegerField(help_text='Quantity being returned')),
                ('return_amount', models.DecimalField(decimal_places=2, help_text='Amount to be returned for this item', max_digits=10)),
                ('return_reason', models.CharField(blank=True, help_text='Specific reason for returning this item', max_length=100)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('LIKE_NEW', 'Like New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='GOOD', help_text='Condition of returned item', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this item')),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Return Item',
                'verbose_name_plural': 'Return Items',
                'db_table': 'sales_return_item',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='saleitem',
            new_name='sale_item_order_i_8e2f26_idx',
            old_name='sale_item_order_i_e66f9d_idx',
        ),
        migrations.RenameIndex(
            model_name='taxrate',
            new_name='tax_rates_tax_typ_10589f_idx',
            old_name='tax_rates_tax_type_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='taxrate',
            new_name='tax_rates_effecti_6bd9fe_idx',
            old_name='tax_rates_effective_dates_idx',
        ),
        migrations.AlterField(
            model_name='sales',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('17.00'), help_text='Legacy: GST percentage (calculated from tax_configuration)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sales',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total calculated tax amount from all tax types', max_digits=12),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='effective_from',
            field=models.DateField(default=datetime.date.today, help_text='Date from which this tax rate is effective'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sale',
            field=models.OneToOneField(help_text='Associated sale', on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='sales.sales'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who generated this receipt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment',
            field=models.ForeignKey(help_text='Associated payment', on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='sale',
            field=models.ForeignKey(help_text='Associated sale', on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='sales.sales'),
        ),
        migrations.AddField(
            model_name='refund',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refund',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='User who processed the refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='return',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved the return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='return',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this return request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='return',
            name='customer',
            field=models.ForeignKey(help_text='Customer requesting the return', on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='return',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='User who processed the return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='return',
            name='sale',
            field=models.ForeignKey(help_text='Original sale for this return', on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='sales.sales'),
        ),
        migrations.AddField(
            model_name='refund',
            name='return_request',
            field=models.ForeignKey(help_text='Return request this refund is for', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='sales.return'),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='return_request',
            field=models.ForeignKey(help_text='Return request this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='sales.return'),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='sale_item',
            field=models.ForeignKey(help_text='Original sale item being returned', on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='sales.saleitem'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='sales_invoi_invoice_51f3c9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['sale'], name='sales_invoi_sale_id_470fd6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='sales_invoi_status_4e3758_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date'], name='sales_invoi_issue_d_0a58aa_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='sales_invoi_due_dat_a262a4_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['is_active'], name='sales_invoi_is_acti_615ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_number'], name='sales_recei_receipt_0e369b_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['sale'], name='sales_recei_sale_id_1567f1_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['payment'], name='sales_recei_payment_f75fa2_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['status'], name='sales_recei_status_fe434f_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['generated_at'], name='sales_recei_generat_9847c4_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['is_active'], name='sales_recei_is_acti_a0e2ce_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['return_number'], name='sales_retur_return__4abfa6_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['sale'], name='sales_retur_sale_id_d5b460_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['customer'], name='sales_retur_custome_4a565b_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['status'], name='sales_retur_status_6097bb_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['return_date'], name='sales_retur_return__9201ce_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['is_active'], name='sales_retur_is_acti_d81c6b_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['refund_number'], name='sales_refun_refund__7be765_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['return_request'], name='sales_refun_return__3f731b_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status'], name='sales_refun_status_e522ec_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['method'], name='sales_refun_method_972077_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['is_active'], name='sales_refun_is_acti_05debe_idx'),
        ),
        migrations.AddIndex(
            model_name='returnitem',
            index=models.Index(fields=['return_request'], name='sales_retur_return__09a9b1_idx'),
        ),
        migrations.AddIndex(
            model_name='returnitem',
            index=models.Index(fields=['sale_item'], name='sales_retur_sale_it_7d1c55_idx'),
        ),
        migrations.AddIndex(
            model_name='returnitem',
            index=models.Index(fields=['is_active'], name='sales_retur_is_acti_c724c6_idx'),
        ),
    ]
