# Generated by Django 5.1.1 on 2024-08-28 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_invoice_receipt_refund_return_returnitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        # Create Return table
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_number', models.CharField(help_text='Unique return number', max_length=50, unique=True)),
                ('reason', models.CharField(choices=[('DEFECTIVE', 'Defective Product'), ('WRONG_ITEM', 'Wrong Item Received'), ('DAMAGED', 'Damaged in Transit'), ('SIZE_ISSUE', 'Size/Fit Issue'), ('QUALITY_ISSUE', 'Quality Issue'), ('CUSTOMER_REQUEST', 'Customer Request'), ('OTHER', 'Other')], help_text='Primary reason for return', max_length=20)),
                ('reason_details', models.TextField(blank=True, help_text='Detailed explanation of return reason')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROCESSED', 'Processed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of return request', max_length=20)),
                ('return_date', models.DateTimeField(auto_now_add=True, help_text='When return was requested')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When return was approved', null=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When return was processed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the return')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount to be refunded', max_digits=10, null=True)),
                ('refund_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHECK', 'Check'), ('CREDIT_NOTE', 'Credit Note'), ('EXCHANGE', 'Exchange'), ('OTHER', 'Other')], help_text='Method of refund', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved the return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_returns', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this return request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_returns', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer requesting the return', on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='customers.customer')),
                ('processed_by', models.ForeignKey(blank=True, help_text='User who processed the return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_returns', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(help_text='Original sale for this return', on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='sales.sales')),
            ],
            options={
                'verbose_name': 'Return',
                'verbose_name_plural': 'Returns',
                'db_table': 'sales_return',
                'ordering': ['-return_date', '-created_at'],
            },
        ),
        
        # Create ReturnItem table
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_returned', models.PositiveIntegerField(help_text='Quantity being returned')),
                ('return_amount', models.DecimalField(decimal_places=2, help_text='Amount to be returned for this item', max_digits=10)),
                ('return_reason', models.CharField(blank=True, help_text='Specific reason for returning this item', max_length=100)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('LIKE_NEW', 'Like New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='GOOD', help_text='Condition of returned item', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this item')),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_request', models.ForeignKey(help_text='Return request this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='sales.return')),
                ('sale_item', models.ForeignKey(help_text='Original sale item being returned', on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='sales.saleitem')),
            ],
            options={
                'verbose_name': 'Return Item',
                'verbose_name_plural': 'Return Items',
                'db_table': 'sales_return_item',
                'ordering': ['-created_at'],
            },
        ),
        
        # Create Refund table
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refund_number', models.CharField(help_text='Unique refund number', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to be refunded', max_digits=10)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHECK', 'Check'), ('CREDIT_NOTE', 'Credit Note'), ('OTHER', 'Other')], help_text='Refund method', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current status of refund', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='External reference number (check number, transfer ID, etc.)', max_length=100)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When refund was processed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the refund')),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_refunds', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, help_text='User who processed the refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL)),
                ('return_request', models.ForeignKey(help_text='Return request this refund is for', on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='sales.return')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'db_table': 'sales_refund',
                'ordering': ['-created_at'],
            },
        ),
        
        # Create Invoice table
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(help_text='Unique invoice number', max_length=20, unique=True)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time invoice was issued')),
                ('due_date', models.DateTimeField(blank=True, help_text='Payment due date (optional)', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('SENT', 'Sent to Customer'), ('VIEWED', 'Viewed by Customer'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='DRAFT', help_text='Current invoice status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional invoice notes')),
                ('terms_conditions', models.TextField(blank=True, help_text='Terms and conditions for this invoice')),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF invoice file', null=True, upload_to='invoices/')),
                ('email_sent', models.BooleanField(default=False, help_text='Whether invoice was emailed to customer')),
                ('email_sent_at', models.DateTimeField(blank=True, help_text='When invoice was last emailed', null=True)),
                ('viewed_at', models.DateTimeField(blank=True, help_text='When customer last viewed the invoice', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('sale', models.OneToOneField(help_text='Associated sale', on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='sales.sales')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'sales_invoice',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        
        # Create Receipt table
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(help_text='Unique receipt number', max_length=20, unique=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When receipt was generated')),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('SENT', 'Sent to Customer'), ('VIEWED', 'Viewed by Customer'), ('ARCHIVED', 'Archived')], default='GENERATED', help_text='Current receipt status', max_length=20)),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF receipt file', null=True, upload_to='receipts/')),
                ('email_sent', models.BooleanField(default=False, help_text='Whether receipt was emailed to customer')),
                ('email_sent_at', models.DateTimeField(blank=True, help_text='When receipt was last emailed', null=True)),
                ('viewed_at', models.DateTimeField(blank=True, help_text='When customer last viewed the receipt', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional receipt notes')),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who generated this receipt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receipts', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(help_text='Associated payment', on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='payments.payment')),
                ('sale', models.ForeignKey(help_text='Associated sale', on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='sales.sales')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'db_table': 'sales_receipt',
                'ordering': ['-generated_at', '-created_at'],
            },
        ),
        
        # Add indexes
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['return_number'], name='sales_retur_return__6e1b50_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['sale'], name='sales_retur_sale_id_f8c8a6_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['customer'], name='sales_retur_custome_2e8a91_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['status'], name='sales_retur_status_6b9f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['return_date'], name='sales_retur_return__a5e8d4_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['is_active'], name='sales_retur_is_acti_b7c8e4_idx'),
        ),
        migrations.AddIndex(
            model_name='returnitem',
            index=models.Index(fields=['return_request'], name='sales_retur_return__9a2b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='returnitem',
            index=models.Index(fields=['sale_item'], name='sales_retur_sale_it_3d4e6f_idx'),
        ),
        migrations.AddIndex(
            model_name='returnitem',
            index=models.Index(fields=['is_active'], name='sales_retur_is_acti_7e8f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['refund_number'], name='sales_refun_refund__1b2c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['return_request'], name='sales_refun_return__4e5f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status'], name='sales_refun_status_7b8c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['method'], name='sales_refun_method_0e1f2a_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['is_active'], name='sales_refun_is_acti_3b4c5d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='sales_invoi_invoice_6e7f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['sale'], name='sales_invoi_sale_id_9b0c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='sales_invoi_status_2e3f4a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date'], name='sales_invoi_issue_d_5b6c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='sales_invoi_due_dat_8e9f0a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['is_active'], name='sales_invoi_is_acti_1c2d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_number'], name='sales_recei_receipt_4f5a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['sale'], name='sales_recei_sale_id_7c8d9e_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['payment'], name='sales_recei_payment_0f1a2b_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['status'], name='sales_recei_status_3c4d5e_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['generated_at'], name='sales_recei_generat_6f7a8b_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['is_active'], name='sales_recei_is_acti_9c0d1e_idx'),
        ),
    ]
