# Generated by Django 6.0.2 on 2026-04-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='withdrawal_by',
            field=models.CharField(choices=[('Maqbool Fashion', 'Maqbool Fashion'), ('MetaBrass', 'MetaBrass')], help_text='Who authorized/made the withdrawal', max_length=50),
        ),
    ]
