# Generated by Django 6.0.2 on 2026-05-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_withdrawal_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='withdrawal_by',
            field=models.CharField(choices=[('MetaBrass Admin', 'MetaBrass Admin')], help_text='Who authorized/made the withdrawal', max_length=50),
        ),
    ]
