# Generated by Django 5.2.4 on 2025-08-08 10:49

import django.core.validators
import django.db.models.deletion
import uuid
import vendors.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name of the vendor', max_length=100)),
                ('business_name', models.CharField(help_text='Name of the business/company', max_length=150)),
                ('cnic', models.CharField(help_text='Pakistani CNIC in format: 12345-1234567-1', max_length=15, unique=True, validators=[vendors.models.validate_pakistani_cnic])),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in valid format', regex='^[\\+]?[0-9\\-\\s]{10,15}$'), vendors.models.validate_pakistani_phone])),
                ('city', models.CharField(help_text='City where vendor is located', max_length=50)),
                ('area', models.CharField(help_text='Area/locality within the city', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the vendor is active (for soft deletion)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vendors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VendorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['name'], name='vendors_ven_name_0d60a8_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['business_name'], name='vendors_ven_busines_c24d58_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['city'], name='vendors_ven_city_4e1b89_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['area'], name='vendors_ven_area_230246_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['cnic'], name='vendors_ven_cnic_0a9ce1_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['phone'], name='vendors_ven_phone_a8987a_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['is_active'], name='vendors_ven_is_acti_5c8a37_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['created_at'], name='vendors_ven_created_c4e3ec_idx'),
        ),
    ]
