# Generated by Django 5.2.4 on 2025-08-16 14:40

import django.core.validators
import django.db.models.deletion
import payments.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labors', '0001_initial'),
        ('orders', '0002_order_conversion_date_order_conversion_status_and_more'),
        ('sales', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payer_type', models.CharField(choices=[('LABOR', 'Labor'), ('VENDOR', 'Vendor'), ('CUSTOMER', 'Customer'), ('OTHER', 'Other')], help_text='Type of entity making the payment', max_length=20)),
                ('payer_id', models.UUIDField(blank=True, help_text='ID of the payer entity', null=True)),
                ('labor_name', models.CharField(blank=True, help_text='Cached labor name at time of payment', max_length=200)),
                ('labor_phone', models.CharField(blank=True, help_text='Cached labor phone at time of payment', max_length=20)),
                ('labor_role', models.CharField(blank=True, help_text='Cached labor role at time of payment', max_length=100)),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bonus amount (if any)', max_digits=10)),
                ('deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Deduction amount (if any)', max_digits=10)),
                ('payment_month', models.DateField(help_text='Month for which payment is made')),
                ('is_final_payment', models.BooleanField(default=False, help_text='Whether this is the final payment for the period')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_PAYMENT', 'Mobile Payment (JazzCash/EasyPaisa)'), ('CHECK', 'Check'), ('CARD', 'Credit/Debit Card'), ('OTHER', 'Other')], default='CASH', help_text='Method of payment', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Payment description and notes')),
                ('date', models.DateField(help_text='Date of payment', validators=[payments.models.validate_payment_date])),
                ('time', models.TimeField(help_text='Time of payment')),
                ('receipt_image_path', models.ImageField(blank=True, help_text='Receipt image for payment verification', null=True, upload_to=payments.models.payment_receipt_upload_path)),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who recorded this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
                ('labor', models.ForeignKey(blank=True, help_text='Labor receiving payment (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='labors.labor')),
                ('order', models.ForeignKey(blank=True, help_text='Order this payment is related to (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='orders.order')),
                ('sale', models.ForeignKey(blank=True, help_text='Sale this payment is related to (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='sales.sales')),
                ('vendor', models.ForeignKey(blank=True, help_text='Vendor receiving payment (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payment',
                'ordering': ['-date', '-time', '-created_at'],
                'indexes': [models.Index(fields=['labor'], name='payment_labor_i_b1e6d1_idx'), models.Index(fields=['vendor'], name='payment_vendor__3df712_idx'), models.Index(fields=['order'], name='payment_order_i_f08ba7_idx'), models.Index(fields=['sale'], name='payment_sale_id_745f50_idx'), models.Index(fields=['payer_type'], name='payment_payer_t_ce6651_idx'), models.Index(fields=['payment_month'], name='payment_payment_27d619_idx'), models.Index(fields=['date'], name='payment_date_9bceae_idx'), models.Index(fields=['payment_method'], name='payment_payment_d8e241_idx'), models.Index(fields=['is_final_payment'], name='payment_is_fina_0dbe70_idx'), models.Index(fields=['is_active'], name='payment_is_acti_f29160_idx'), models.Index(fields=['created_at'], name='payment_created_6be7be_idx')],
            },
        ),
    ]
