# Generated by Django 5.2.4 on 2025-08-28 12:56

import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt_image_path',
            field=models.FileField(blank=True, help_text='Receipt file for payment verification (JPG, PNG, PDF, max 5MB)', null=True, upload_to=payments.models.payment_receipt_upload_path, validators=[payments.models.validate_receipt_file_size]),
        ),
    ]
