# Generated by Django 6.0.2 on 2026-04-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakat',
            name='authorized_by',
            field=models.CharField(choices=[('Maqbool Fashion', 'Maqbool Fashion'), ('MetaBrass', 'MetaBrass')], help_text='Who authorized the Zakat payment', max_length=50),
        ),
    ]
