# Generated by Django 6.0.2 on 2026-05-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakats', '0002_alter_zakat_authorized_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakat',
            name='authorized_by',
            field=models.CharField(choices=[('MetaBrass Admin', 'MetaBrass Admin')], help_text='Who authorized the Zakat payment', max_length=50),
        ),
    ]
