# Generated by Django 5.2.4 on 2025-08-13 14:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '__first__'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(help_text='Cached product name at time of order', max_length=200)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of this product ordered')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price at time of order (cached from product)', max_digits=12)),
                ('customization_notes', models.TextField(blank=True, help_text='Special instructions or customization notes for this item')),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Calculated total for this line item', max_digits=15)),
                ('is_active', models.BooleanField(default=True, help_text='Used for soft deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(help_text='Parent order', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
                ('product', models.ForeignKey(help_text='Product being ordered', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'order_item',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['order'], name='order_item_order_i_08a5da_idx'), models.Index(fields=['product'], name='order_item_product_442025_idx'), models.Index(fields=['is_active'], name='order_item_is_acti_d044de_idx'), models.Index(fields=['created_at'], name='order_item_created_39b431_idx')],
                'unique_together': {('order', 'product')},
            },
        ),
    ]
