# Generated by Django 5.2.4 on 2025-08-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_items', '0001_initial'),
        ('orders', '0002_order_conversion_date_order_conversion_status_and_more'),
        ('products', '0002_add_cost_price_field'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'is_active'], name='order_item_order_i_df2a49_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product', 'is_active'], name='order_item_product_428d76_idx'),
        ),
    ]
